-- ============================================================
-- ChupeteClicker — Migration 010
-- 1. Populate durability for existing inventory items
-- 2. Add case_drop flag to items (new click-only items = false)
-- ============================================================

-- ── Populate durability for existing items (pre-migration 007) ──────────────
UPDATE public.inventory
SET
  max_durability = CASE
    WHEN float_value < 0.07 THEN 5000
    WHEN float_value < 0.15 THEN 3000
    WHEN float_value < 0.38 THEN 1500
    WHEN float_value < 0.45 THEN 800
    ELSE 300
  END,
  durability = CASE
    WHEN float_value < 0.07 THEN 5000
    WHEN float_value < 0.15 THEN 3000
    WHEN float_value < 0.38 THEN 1500
    WHEN float_value < 0.45 THEN 800
    ELSE 300
  END
WHERE durability IS NULL;

-- ── Add case_drop column ─────────────────────────────────────────────────────
-- true  = item can drop from cases
-- false = item only obtainable through clicking (roll-drop)
ALTER TABLE public.items
  ADD COLUMN IF NOT EXISTS case_drop BOOLEAN NOT NULL DEFAULT false;

-- Original curated items (from initial seed) go into cases
UPDATE public.items SET case_drop = true WHERE name IN (
  'Chupete Básico', 'Chupete de Silicona', 'Chupete de Goma',
  'Chupete Pintado', 'Chupete Fosforescente',
  'Chupete Dorado', 'Chupete de Cristal',
  'Chupete Espacial', 'Chupete del Che',
  'Chupete Plasma', 'Chupete Cuántico',
  'Chupete del Maradona', 'Chupete de Evita',
  'Chupete Alienígena', 'Chupete Intergaláctico',
  'El Chupete Original'
);

-- Any item that has a real image (generated by Pollinations or uploaded manually)
-- should also be available in cases
UPDATE public.items SET case_drop = true
WHERE image_url IS NOT NULL AND image_url != '';
